	<!-- Footer -->
	<div class="footer container-fluid">
		<div class="container clearfix">
			<div class="logo"><img src="/images/logo_footer.png" alt="EK_silverEDU" /></div>
			<div class="address">
				16827 경기도 용인시 수지구 신수로 767 분당U타워 지식산업센터 2101호 EK(주)<br/>
				Tel.02-588-0115 Fax.031-218-4700
				<p class="copy">Copyright &copy; EK Corp. all rights reserved</p>
			</div>
		</div>
	</div>
	
	<!-- jQuery -->
	<script type="text/javascript" src="/inc/js/jquery.min.js"></script>
	<!-- Selectbox Custom -->
	<script type="text/javascript" src="/inc/js/jquery.customSelect.min.js"></script>
	<script type="text/javascript" src="/inc/js/jquery.tabslet.min.js"></script>
	<script type="text/javascript" src="/inc/js/script.js"></script>
</body>
</html>