<!DOCTYPE html>
<html lang="ko">
<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Always force latest IE rendering engine or request Chrome Frame -->
	<!--[if IE]>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<![endif]-->
	<!-- Meta -->
	<meta name="description" content="노인 치매예방 교육 실버 에듀">
	<meta name="keywords" content="silveredu, 실버에듀, 키드키즈, 해오름, 요양병원">
	<meta name="author" content="kang2oon">
	<meta charset="utf-8">
	<!-- Site Title -->
	<title>실버에듀</title>
	<!-- CSS -->
	<link type="text/css" rel="stylesheet" href="/inc/fonts/spoqa-kr.css">
	<link type="text/css" rel="stylesheet" href="/inc/fonts/iropke.css">
	<link type="text/css" rel="stylesheet" href="/inc/css/kang2oon.reset.min.css">
	<link type="text/css" rel="stylesheet" href="/inc/css/iziModal.min.css">
	<link type="text/css" rel="stylesheet" href="/inc/css/style.css">
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body class="">
	<!-- Header -->
	<div class="header container-fluid">
		<div class="container clearfix">
			<h1><a href="/"><img src="/images/logo_main1.png" alt="실버에듀" /></a></h1>
			<ul class="gnb clearfix">
				<li class="program on">프로그램<span></span></li>
			</ul>
			<ul class="mnb clearfix">
				<li><a href="javascript:void(0);">로그인</a></li>
				<li><a href="/member/join_agreement.html">회원가입</a></li>
			</ul>
		</div>
	</div>

	<!-- Menu Over-Bar -->
	<div class="menu_over container-fluid">
		<div class="container clearfix">
			<div class="book">
				<div class="thumb"><img src="/images/book_201803_thumb.jpg" alt="2018년 3월 교재" /></div>
				<select id="ym_choice">
					<option value="201803">2018년 3월</option>
				</select>
				<a href="javascript:void(0);" class="btn btn_full btn_orange btn_bold" data-izimodal-open="#curri">커리큘럼 보기</a>
			</div>
			<div class="week_plan clearfix">
				<div class="plan">
					<ul class="sel_week clearfix">
						<li><a href="#week1">1주</a></li>
						<li><a href="#week2">2주</a></li>
						<li><a href="#week3">3주</a></li>
						<li><a href="#week4">4주</a></li>
					</ul>
					<div id="week1">
						<div class="tit_week">1회</div>
						<ul class="doc_list">
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_memory.png" alt="기억능력"><img src="/images/ico_activity_language.png" alt="언어"><a href="javascript:void(0);">봄꽃 이름을 알아요</a></li>
							<li><img src="/images/ico_region_mental.png" alt="정신행동"><img src="/images/ico_region2_uninspired.png" alt="무감동"><img src="/images/ico_activity_game.png" alt="게임"><a href="javascript:void(0);">내 짝 얼굴을 그려요</a></li>
							<li><img src="/images/ico_region_lifestyle.png" alt="생활습관"><img src="/images/ico_lifestyle_table.png" alt="생활습관표"><a href="javascript:void(0);">(3월-1) 치매예방 건강수칙</a></li>
						</ul>
						<div class="tit_week">2회</div>
						<ul class="doc_list">
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_execution.png" alt="실행능력"><img src="/images/ico_activity_art.png" alt="미술"><a href="javascript:void(0);">나의 하루일과는?</a></li>
							<li><img src="/images/ico_region_mental.png" alt="정신행동"><img src="/images/ico_region2_delusion.png" alt="망상의심"><img src="/images/ico_activity_music.png" alt="음악"><a href="javascript:void(0);">노래를 배워보아요</a></li>
							<li><img src="/images/ico_region_lifestyle.png" alt="생활습관"><img src="/images/ico_lifestyle_table.png" alt="생활습관표"><a href="javascript:void(0);">(3월-1) 치매예방 건강수칙</a></li>
						</ul>
					</div>
					<div id="week2">
						<div class="tit_week">3회</div>
						<ul class="doc_list">
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_judgment.png" alt="판단능력"><img src="/images/ico_activity_art.png" alt="미술"><a href="javascript:void(0);">내가 주인공이라면?</a></li>
							<li><img src="/images/ico_region_mental.png" alt="정신행동"><img src="/images/ico_region2_delusion.png" alt="망상의심"><img src="/images/ico_activity_music.png" alt="음악"><a href="javascript:void(0);">건강박수치기는 건강에 좋아요</a></li>
							<li><img src="/images/ico_region_lifestyle.png" alt="생활습관"><img src="/images/ico_lifestyle_table.png" alt="생활습관표"><a href="javascript:void(0);">(3월-2) 치매예방 건강수칙</a></li>
						</ul>
						<div class="tit_week">4회</div>
						<ul class="doc_list">
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_memory.png" alt="기억능력"><img src="/images/ico_activity_sort.png" alt="분류"><a href="javascript:void(0);">틀린그림을 찾아요</a></li>
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_time.png" alt="시간능력"><img src="/images/ico_activity_language.png" alt="언어"><a href="javascript:void(0);">우리 가족을 알아보아요</a></li>
							<li><img src="/images/ico_region_lifestyle.png" alt="생활습관"><img src="/images/ico_lifestyle_table.png" alt="생활습관표"><a href="javascript:void(0);">(3월-2) 치매예방 건강수칙</a></li>
						</ul>
					</div>
					<div id="week3">
						<div class="tit_week">5회</div>
						<ul class="doc_list">
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_calculation.png" alt="계산능력"><img src="/images/ico_activity_game.png" alt="게임"><a href="javascript:void(0);">얼마일까요?</a></li>
							<li><img src="/images/ico_region_mental.png" alt="정신행동"><img src="/images/ico_region2_melancholia.png" alt="우울증"><img src="/images/ico_activity_art.png" alt="미술"><a href="javascript:void(0);">점토로 내 얼굴을 꾸며요</a></li>
							<li><img src="/images/ico_region_lifestyle.png" alt="생활습관"><img src="/images/ico_lifestyle_table.png" alt="생활습관표"><a href="javascript:void(0);">(3월-3) 치매예방 건강수칙</a></li>
						</ul>
						<div class="tit_week">6회</div>
						<ul class="doc_list">
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_language.png" alt="언어능력"><img src="/images/ico_activity_language.png" alt="언어"><a href="javascript:void(0);">세계 여러나라 언어로 인사해요</a></li>
							<li><img src="/images/ico_region_mental.png" alt="정신행동"><img src="/images/ico_region2_unrest.png" alt="불안"><img src="/images/ico_activity_read.png" alt="독후활동"><a href="javascript:void(0);">나의 걱정 이야기하기</a></li>
							<li><img src="/images/ico_region_lifestyle.png" alt="생활습관"><img src="/images/ico_lifestyle_table.png" alt="생활습관표"><a href="javascript:void(0);">(3월-3) 치매예방 건강수칙</a></li>
						</ul>
					</div>
					<div id="week4">
						<div class="tit_week">7회</div>
						<ul class="doc_list">
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_judgment.png" alt="판단능력"><img src="/images/ico_activity_story.png" alt="이야기나누기"><a href="javascript:void(0);">어떻게 해야할까요?</a></li>
							<li><img src="/images/ico_region_mental.png" alt="정신행동"><img src="/images/ico_region2_aggression.png" alt="공격성"><img src="/images/ico_activity_operation.png" alt="조작"><a href="javascript:void(0);">칠교조각 색칠하기</a></li>
							<li><img src="/images/ico_region_lifestyle.png" alt="생활습관"><img src="/images/ico_lifestyle_table.png" alt="생활습관표"><a href="javascript:void(0);">(3월-4) 치매예방 건강수칙</a></li>
						</ul>
						<div class="tit_week">8회</div>
						<ul class="doc_list">
							<li><img src="/images/ico_region_cognitive.png" alt="인지기능"><img src="/images/ico_region2_space.png" alt="공간능력"><img src="/images/ico_activity_puzzle.png" alt="퍼즐"><a href="javascript:void(0);">그림자를 찾아요</a></li>
							<li><img src="/images/ico_region_mental.png" alt="정신행동"><img src="/images/ico_region2_unrest.png" alt="불안"><img src="/images/ico_activity_art.png" alt="미술"><a href="javascript:void(0);">전통문양 색칠하기</a></li>
							<li><img src="/images/ico_region_lifestyle.png" alt="생활습관"><img src="/images/ico_lifestyle_table.png" alt="생활습관표"><a href="javascript:void(0);">(3월-4) 치매예방 건강수칙</a></li>
						</ul>
					</div>
				</div>
				<div class="deep_wrapper">
					<div class="deep">
						<div class="label"></div>
						<div class="tit">심화학습</div>
						<ul class="deep_list">
							<li><a href="javascript:void(0);">손바닥 혈자리를 눌러보세요</a></li>
							<li><a href="javascript:void(0);">계산해 보세요</a></li>
							<li><a href="javascript:void(0);">요리조리 실뜨기 놀이</a></li>
							<li><a href="javascript:void(0);">아기토끼풀 동화 거꾸로 읽기</a></li>
						</ul>
						<a href="javascript:void(0);" class="btn btn_full btn_lstable" data-izimodal-open="#ls_sum">이 달의 <strong>생활습관표</strong></a>
					</div>
				</div>
			</div>
			<a href="javascript:void(0);" class="btn close_menuover"><img src="/images/btn_close_menuover.png" alt="닫기" /></a>
		</div>
	</div>