<!-- 커리큘럼 보기 -->
<div id="curri" class="modal" data-iziModal-fullscreen="true"  data-iziModal-title="커리큘럼 보기" data-iziModal-width="1000px">
	<h2>3월 치매예방 프로그램(인지기능/정신행동/생활습관)</h2>
	<table class="" summary="3월 치매예방 프로그램(인지기능/정신행동/생활습관)">
	<caption>3월 치매예방 프로그램(인지기능/정신행동/생활습관)</caption>
	<thead>
	<tr>
		<th>월</th>
		<th colspan="2">주</th>
		<th colspan="2">치매의 특징</th>
		<th>활동유형</th>
		<th>활동명</th>
		<th>시간</th>
		<th>비고</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td rowspan="24">3월</td>
		<td rowspan="6">1주</td>
		<td rowspan="3">1회</td>
		<td>인지기능</td>
		<td>기억능력</td>
		<td>언어</td>
		<td class="aleft">봄꽃 이름을 알아요</td>
		<td>30분</td>
		<td></td>
	</tr>
	<tr>
		<td>정신행동</td>
		<td>무감동</td>
		<td>게임</td>
		<td class="aleft">내 짝 얼굴을 그려요</td>
		<td>50분</td>
		<td></td>
	</tr>
	<tr>
		<td>생활습관</td>
		<td colspan="2">3월 생활습관표 1</td>
		<td class="aleft">치매예방 건강수칙</td>
		<td>10분</td>
		<td></td>
	</tr>
	<tr>
		<td rowspan="3">2회</td>
		<td>인지기능</td>
		<td>실행능력</td>
		<td>미술</td>
		<td class="aleft">나의 하루일과는?</td>
		<td>50분</td>
		<td></td>
	</tr>
	<tr>
		<td>정신행동</td>
		<td>망상ㆍ의심</td>
		<td>음악</td>
		<td class="aleft">노래를 배워보아요</td>
		<td>40분</td>
		<td></td>
	</tr>
	<tr>
		<td>생활습관</td>
		<td colspan="2">3월 생활습관표 1</td>
		<td class="aleft">치매예방 건강수칙</td>
		<td>10분</td>
		<td></td>
	</tr>
	<tr>
		<td rowspan="6">2주</td>
		<td rowspan="3">3회</td>
		<td>인지기능</td>
		<td>판단능력</td>
		<td>미술</td>
		<td class="aleft">내가 주인공이라면?</td>
		<td>40분</td>
		<td></td>
	</tr>
	<tr>
		<td>정신행동</td>
		<td>망상ㆍ의심</td>
		<td>음악</td>
		<td class="aleft">건강박수치기는 건강에 좋아요</td>
		<td>30분</td>
		<td></td>
	</tr>
	<tr>
		<td>생활습관</td>
		<td colspan="2">3월 생활습관표 2</td>
		<td class="aleft">치매예방 건강수칙</td>
		<td>10분</td>
		<td></td>
	</tr>
	<tr>
		<td rowspan="3">4회</td>
		<td rowspan="2">인지기능</td>
		<td>기억능력</td>
		<td>분류</td>
		<td class="aleft">틀린그림을 찾아요</td>
		<td>30분</td>
		<td></td>
	</tr>
	<tr>
		<td>시간능력</td>
		<td>언어</td>
		<td class="aleft">우리 가족을 알아보아요</td>
		<td>40분</td>
		<td></td>
	</tr>
	<tr>
		<td>생활습관</td>
		<td colspan="2">3월 생활습관표 1</td>
		<td class="aleft">치매예방 건강수칙</td>
		<td>10분</td>
		<td></td>
	</tr>
	<tr>
		<td rowspan="6">3주</td>
		<td rowspan="3">5회</td>
		<td>인지기능</td>
		<td>계산능력</td>
		<td>게임</td>
		<td class="aleft">얼마일까요?</td>
		<td>40분</td>
		<td></td>
	</tr>
	<tr>
		<td>정신행동</td>
		<td>우울증</td>
		<td>미술</td>
		<td class="aleft">점토로 내 얼굴을 꾸며요</td>
		<td>50분</td>
		<td></td>
	</tr>
	<tr>
		<td>생활습관</td>
		<td colspan="2">3월 생활습관표 3</td>
		<td class="aleft">치매예방 건강수칙</td>
		<td>10분</td>
		<td></td>
	</tr>
	<tr>
		<td rowspan="3">6회</td>
		<td>인지기능</td>
		<td>언어능력</td>
		<td>언어</td>
		<td class="aleft">세계 여러나라 언어로 인사해요</td>
		<td>30분</td>
		<td></td>
	</tr>
	<tr>
		<td>정신행동</td>
		<td>불안</td>
		<td>독후활동</td>
		<td class="aleft">나의 걱정 이야기하기</td>
		<td>50분</td>
		<td></td>
	</tr>
	<tr>
		<td>생활습관</td>
		<td colspan="2">3월 생활습관표 3</td>
		<td class="aleft">치매예방 건강수칙</td>
		<td>10분</td>
		<td></td>
	</tr>
	<tr>
		<td rowspan="6">4주</td>
		<td rowspan="3">7회</td>
		<td>인지기능</td>
		<td>판단능력</td>
		<td>이야기 나누기</td>
		<td class="aleft">어떻게 해야할까요?</td>
		<td>30분</td>
		<td></td>
	</tr>
	<tr>
		<td>정신행동</td>
		<td>공격성</td>
		<td>조작</td>
		<td class="aleft">칠교조각 색칠하기</td>
		<td>30분</td>
		<td></td>
	</tr>
	<tr>
		<td>생활습관</td>
		<td colspan="2">3월 생활습관표 4</td>
		<td class="aleft">치매예방 건강수칙</td>
		<td>10분</td>
		<td></td>
	</tr>
	<tr>
		<td rowspan="3">8회</td>
		<td>인지기능</td>
		<td>공간능력</td>
		<td>퍼즐</td>
		<td class="aleft">그림자를 찾아요</td>
		<td>30분</td>
		<td></td>
	</tr>
	<tr>
		<td>정신행동</td>
		<td>불안</td>
		<td>미술</td>
		<td class="aleft">전통문양 색칠하기</td>
		<td>50분</td>
		<td></td>
	</tr>
	<tr>
		<td>생활습관</td>
		<td colspan="2">3월 생활습관표 4</td>
		<td class="aleft">치매예방 건강수칙</td>
		<td>10분</td>
		<td></td>
	</tr>
	<tr>
		<td colspan="4">심화활동</td>
		<td colspan="5" class="aleft">
			손바닥 혈자리를 눌러 보세요<br/>
			계산해 보세요<br/>
			요리 조리 실뜨기 놀이<br/>
			아기토끼풀 동화 거꾸로 읽기
		</td>
	</tr>
	<tr>
		<td colspan="4">생활습관표(3월4주)</td>
		<td colspan="5" class="aleft">칭찬합니다</td>
	</tr>
	</tbody>
	</table>
</div>

<!-- 생활습관표 모아보기 -->
<div id="ls_sum" class="modal" data-iziModal-fullscreen="true" data-iziModal-title="이 달의 생활습관표" data-iziModal-width="780px" data-iziModal-background="#f5f5f5">
	<div class="lifestyle_table">
		<ul class="thumb_view">
			<li><a href="#lstw1"><img src="/images/@smp_print1.png" alt=""></a></li>
			<li><a href="#lstw2"><img src="/images/@smp_print.png" alt=""></a> </li>
			<li><a href="#lstw3"><img src="/images/@smp_print2.png" alt=""></a></li>
			<li><a href="#lstw4"><img src="/images/@smp_print3.png" alt=""></a></li>
		</ul>
		<div id="lstw1" class="large_view"><img src="/images/@smp_print1_large.png" alt=""></div>
		<div id="lstw2" class="large_view"><img src="/images/@smp_print_large.png" alt=""> </div>
		<div id="lstw3" class="large_view"><img src="/images/@smp_print2_large.png" alt=""></div>
		<div id="lstw4" class="large_view"><img src="/images/@smp_print3_large.png" alt=""></div>
	</div>
</div>

<!-- 동영상 보기(유튜브) -->
<div id="vod_sflower" class="modal" data-iziModal-fullscreen="true" data-iziModal-title="봄에 피는 꽃" data-iziModal-subtitle="미디어 자료"  data-iziModal-padding="25px">
	<div class="videoWrapper">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/9Rg06o9Os0Y?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
	</div>
</div>

<!-- 활동지 보기 -->
<div id="act_sflower" class="modal" data-iziModal-fullscreen="true" data-iziModal-title="봄꽃 이름을 알아요" data-iziModal-subtitle="미디어 자료"  data-iziModal-padding="25px">
	<div class="acenter"><img src="/images/@smp_print_large.png" alt="" /></div>
</div>